name: Node.js CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install jq
      run: sudo apt-get install jq

    - name: Install node_modules
      run: |
        cd Backend
        npm install

    - name: Run npm audit
      run: |
        cd Backend
        npm audit --json > npm-audit.json
      continue-on-error: true

    - name: Run tests
      run: |
        cd Backend
        RESULT_DATA=$(cat npm-audit.json)
        echo $RESULT_DATA
        vulnerabilitiesCount=$(echo $RESULT_DATA | jq '.metadata.vulnerabilities.moderate')
        totalVulnerabilitiesCount=$(echo $RESULT_DATA | jq '.metadata.vulnerabilities.total')
        echo $totalVulnerabilitiesCount
        echo $vulnerabilitiesCount
