name: Code Review Workflow

on:
  push:
    branches:
      - main

jobs:
  reviewing_code:                                       
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Github Repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq

      - name: Install node_modules
        run: |
            cd Backend
            npm install

      - name: Check for Vulnerabilities
        run: |
            cd Backend
            npm audit --force
            echo "HELLO"
    
