name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  reviewing_code:
    runs-on: ubuntu-latest

    steps:
      - name: Run Lambda function
        id: reviewing_code
        run: |
          # Run your Lambda function and set the result as an environment variable
          echo "CAN_MERGE=false" >> $GITHUB_ENV

      - name: Set output and finish
        if: ${{ env.CAN_MERGE == 'true' }}
        run: echo "Can merge safely!"
