name: CI/CD with Lambda
on:
  pull_request:
    branches:
      - no-deployment
jobs:
  reviewing_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIASSSRAFRPKMRUU46H
          aws-secret-access-key: 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
          aws-region: eu-central-1
      - name: Invoke Lambda Function
        run: |
          aws lambda invoke --function-name Library_Audit_Integration --log-type Tail --query 'Payload' --output text result.txt

      - name: Read data from result.txt and save in a variable
        id: read_result
        run: |
          RESULT_DATA=$(cat result.txt)
          echo "Result Data: $RESULT_DATA"
