name: Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  reviewing_code:
    runs-on: ubuntu-latest

    steps:
    - name: Check Commits
      run: |
        echo "Error: Work in progress commits are not allowed."
        exit 1
