name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  reviewing_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Lambda function
        id: reviewing_code
        run: |
          # Run your Lambda function and set the result as an output
          echo "::set-output name=canMerge::false"
