name: Code Review Workflow

on:
  push:
    branches:
      - main

jobs:
  reviewing_code:                                       
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Github Repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq

      - name: Install node_modules
        run: |
            cd Backend
            npm install

      - name: Check for Vulnerabilities
        run: |
            cd Backend
            ls
            audit_result=$(npm audit --json)
            
            VULNERABILITIES_COUNT=$(echo "$audit_result" | jq '.metadata.vulnerabilities.total')
            
            # Check if there are vulnerabilities
            if [[ $VULNERABILITIES_COUNT == 0 ]]; then
              echo "No Vulnerabilities Found."
            else
              # Fix vulnerabilities
              npm audit fix
            
              # Run npm audit again
              audit_result_after_fix=$(npm audit --json)
            
              VULNERABILITIES_COUNT=$(echo "$audit_result_after_fix" | jq '.metadata.vulnerabilities.total')
            
              # Check if there are still vulnerabilities
              if [[ $VULNERABILITIES_COUNT == 0 ]]; then
                echo "Vulnerabilities Fixed."
              else
                SLACK_WEBHOOK_URL="https://hooks.slack.com/services/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"
                VULNERABILITIES_COUNT=$(echo "$audit_result_after_fix" | jq '.metadata.vulnerabilities.total')
              
                curl -X POST -H 'Content-type: application/json' \
                  --data "{
                    \"text\": \"*Vulnerabilities Found*\nTotal: $VULNERABILITIES_COUNT\",
                  }" \
                  "$SLACK_WEBHOOK_URL"
                exit 1
              fi
            fi
    
