name: Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  reviewing_code:
    runs-on: ubuntu-latest

    steps:
    - name: Check Commits
      run: |
        # Check if any commit message contains "Testing"
        if git log --format=%B -n 1 $GITHUB_SHA | grep -qi "Testing"; then
          echo "Error: Work in progress commits are not allowed."
          exit 1
        fi
