name: SonarCloud Scan

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get SonarCloud Issues
        id: get_issues
        run: |
          export SONARCLOUD_PROJECT_KEY=Testing_repo
          export SONARCLOUD_ORGANIZATION=hamzapooki
          export SONARCLOUD_API_TOKEN=e43df0134726f2cda2df906eaf2577f14aad7300

          # Fetch the list of issues using the SonarCloud API
          curl -u $SONARCLOUD_API_TOKEN: \
            "https://sonarcloud.io/api/issues/search?componentKeys=$SONARCLOUD_PROJECT_KEY&organization=$SONARCLOUD_ORGANIZATION" \
            > issues.json

      - name: Send Issues to Slack
        run: |
          jq -r '.issues[] | "curl -X POST -H \"Content-type: application/json\" --data \\\"{\\\\\"text\\\\\": \\\\\\\"New SonarCloud Issue Detected!\\\\nIssue Key: \(.key)\\\\nSeverity: \(.severity)\\\\nMessage: \(.message)\\\\nSee the details here: \(.url)\\\\\"}\" https://hooks.slack.com/services/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"' < issues.json | sh
