name: CodeQL Scan

on:
  push:
    branches:
      - main

jobs:
  codeql_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up CodeQL
        uses: github/codeql-action/setup@v2
        with:
          languages: javascript,java  # Adjust based on your project's language
      - name: Build and Test
        run: |
          # Add your build and test commands here
          # Example for a Node.js project:
          npm install
          npm test
      - name: Run CodeQL Analysis
        env:
          CODEQL_ACTION_TOKEN: ${{ secrets.PAT_TOKEN }}
        uses: github/codeql-action/analyze@v2
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: codeql-results
          path: ${{ github.workspace }}/codeql-sarif

