name: CodeQL Analysis

on:
  push:
    branches:
      - main

jobs:
  codeql-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          
      - name: Get CodeQL tools
        run: |
          echo "##[group] Installing CodeQL tools"
          DOWNLOAD_URL=$(curl -s https://api.github.com/repos/github/codeql-action/releases/latest | jq -r '.assets[] | select(.name | endswith("codeql.zip")) | .browser_download_url')
          wget "$DOWNLOAD_URL" -O codeql.zip
          unzip -qq codeql.zip -d codeql
          echo "##[endgroup]"

      - name: Run CodeQL Analysis
        run: |
          echo "##[group] Running CodeQL analysis"
          codeql database create --language=java --source-root . --output=codeql-database
          codeql database analyze --database=codeql-database security-and-quality.qls --format=sarif-latest --output=codeql-results.sarif
          echo "##[endgroup]"

      - name: Upload CodeQL results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: codeql-results.sarif
