name: ZAP Security Scan

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install ZAP
        run: |
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.11.0/ZAP_2.11.0_Linux.tar.gz
          tar -xzf ZAP_2.11.0_Linux.tar.gz
          sudo mv ZAP_2.11.0 /opt/
          export PATH=$PATH:/opt/ZAP_2.11.0

      - name: Run ZAP Security Scan
        run: |
          export ZAP_API_URL=http://localhost:8090
          export ZAP_API_KEY=$(curl -sX POST -H "Content-Type: application/json" -H "Accept: application/json" -d '{"api_key":"","api_user":"","credentials":[{"username":"admin","password":"admin"}]}' $ZAP_API_URL/JSON/core/action/autentication/set/ -o - | jq -r '.api_key')
          
          # Start ZAP in headless mode
          /opt/ZAP_2.11.0/zap.sh -daemon -host 0.0.0.0 -port 8090 -config api.disablekey=true -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true

          # Wait for ZAP to start
          sleep 30

          # Run ZAP security scan using the CLI
          /opt/ZAP_2.11.0/zap-cli.sh quick-scan -r ${GITHUB_WORKSPACE} -t ${ZAP_API_KEY} -f html -o /tmp/zap-report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: /tmp/zap-report.html
