name: Dependency-Check Security Scan

on:
  push:
    branches:
      - main

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Run Dependency-Check
        run: |
          wget https://dl.bintray.com/jeremy-long/owasp/dependency-check-6.0.3-release.zip
          unzip dependency-check-*.zip
          cd dependency-check-*
          ./bin/dependency-check.sh --scan .
