name: Checkmarx Scan

on:
  push:
    branches:
      - main

jobs:
  checkmarx_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Checkmarx CLI
      run: |
        wget https://download.checkmarx.com/9.0.0/Plugins/CxConsolePlugin-9.0.0.zip
        unzip CxConsolePlugin-9.0.0.zip
        chmod +x CxConsolePlugin-9.0.0/CxConsole*

    - name: Run Checkmarx Scan
      run: |
        ./CxConsolePlugin-9.0.0/CxConsole.sh Scan -CxServer https://<Checkmarx_Server>/cxrestapi -CxUser <Your_Username> -CxPassword <Your_Password> -ProjectName MyProject -LocationType folder -LocationPath . -preset Default

    - name: Upload Results
      uses: actions/upload-artifact@v2
      with:
        name: checkmarx-results
        path: CxResults.xml
